### ISSUE TITLE
コーデ一覧ページのモック画面を作成する

### ISSUE THREAD

**Issue by laut0104** [laut0104/laZinator#4]
コーデ一覧ページのモック画面を作成する

**Comment by MAO-business** [comment]
ゴール：つなぎこみ部分を作成する
大枠をやーくんが作成
目的：プロジェクト構成の順序を分かりやすくする
↓
Angular materialのテンプレをページ設計通りに書き換えていく
みやくんが作成しているものをやーくんが作成したテンプレと合体させたい
